### ISSUE TITLE
Metal: Error creating pipeline state (Hidden/Dkvfx/Convert): Link failed

### ISSUE THREAD

**Issue by ARadovski** [keijiro/Dkvfx#1]
Hi,

First of all thank you so much for all your creativity!

Now, been trying to get it to run for a while, but I get this error and black screen with nothing rendering:
"Metal: Error creating pipeline state (Hidden/Dkvfx/Convert): Link failed: The type of fragment input user(TEXCOORD0) does not match the type of the corresponding vertex shader output
(null)"

I'm on OSX 10.14.4 Unity 2018.3.6 - MBPro 2012 15"
But I also tried it on OSX 10.11, tried Unity 2019.1b, updated XCode - nothing changes
I've successfully ran your DepthkitTest and Unity HDRP test project on the same machine.

Thank you!

**Comment by keijiro** [comment]
I found some compatibility issues and fixed them. Please try the latest update of the repository.

**Comment by keijiro** [comment]
Please note that I updated the project with Unity 2019.1.0b10. It requires the very latest version of 2019.1 beta.

**Comment by ARadovski** [comment]
Thank you for the update.
The error is gone but I'm still getting just black screen when it runs - on camera preview it has a thin flashing white border but nothing else is showing up. Same issue as described by commenter Dave Pentecost on your tweet about this update. I'm using MacBookPro 15" with NVIDIA GeForce GT 650M 1 GB - quite weak GPU but your DepthkitTest runs fine on it and Unity VFX Graph Sampler stutters but runs.

Are there any additional packages that I have to install manually in addition to what's in this repository? I've tried installing both through download and through Git desktop app. Thanks!

**Comment by keijiro** [comment]
I'm using MacBook Pro 15"  late 2013 with GeForce GT 750M, so the situation is pretty close, not the exactly same though.

I'm not sure why but sometimes the effect disappears when the VFX Editor is closed. So could you try opening the "Particles" graph and play the Test scene without closing the VFX Editor?

Another thing you can try is switching GPU from NVIDIA to Intel. You can change it from Preferences -> General -> Device To Use. I confirmed that it works on Intel Iris GPU with my MacBook.

**Comment by ARadovski** [comment]
Opening "Particles" graph before playing the Test scene has worked.
Thank you!

**Comment by dpentecost** [comment]
Yes, opening the graph fixes it - works before and during play mode. Thanks everyone! Now to go back to pushing the limits of these effects over NDI...
