### ISSUE TITLE
Using the DKvfx on my own projects

### ISSUE THREAD

**Issue by Pitamor** [keijiro/Dkvfx#10]
Hi Keijiro, 
first of all thank you for the creative stuff. I'm really enjoying it. 
I would really like to use the DKvfx with my own Depthkit footage on my own projects but i'm having some difficulties. 
I've imported the HAP player package and also your dkvfx one to my project but the video isn't playing the right way. it is playing as a flat video and not as Volumetric footage. 
I see the Depthkit dll in the project but i'm not sure how to connect it to the footage i've uploaded. 
when i'm using your project evreything works great but when i tried to open my own it didn't work properly. 
solving it will help me a lot and i will be very appreciate.

Thanks once again,

Itamar

**Comment by keijiro** [comment]
How about VFX? Did you create your own?

**Comment by Pitamor** [comment]
Yes indeed but i think my problem is different than that.
I'm creating a VR experience with Depthkit recorded footage and i went to use that footage in the VFX graph and i want to do it in my VR unity project. 
I've imported the KlakHap and the DKvfx packages to my project and created gameobjects for the converter and HAP palyer scripts but i have two problems: the Converter do not recognise the KlakHop and the second one is that it do not play the footage as a volumetric videos but as the regular mp4 file from the depthkit export.
doing it right is very important for me and for my final project for my studies and i will very appreciate any kind of help about it. 

Thanks again

**Comment by keijiro** [comment]
Could you provide a minimal project that reproduces the issue?

**Comment by Pitamor** [comment]
Of course. Thank you so much.
Here's a link to the project: 
https://we.tl/t-qAuT9o4rOP

The problem is that the HAP player script do not recognise the converter script inside of your package...
I also didn't quite understand how the hap files becomes depthkit footage and how exactly i connect it to the vfx graph.

It means a lot to me and will really help me with my works.

Thanks once again. I really appreciate it.

**Comment by keijiro** [comment]
You have to put the video file in the StreamingAssets directory.

https://docs.unity3d.com/Manual/StreamingAssets.html

**Comment by keijiro** [comment]
It's recommended to use the package manager to resolve the dependencies correctly. I added the "How To Install" section to README. Please check it and follow the instruction.

**Comment by Pitamor** [comment]
Thank you so much!!
I've changed the manifest file in my project to this:
{
  "scopedRegistries": [
    {
      "name": "Keijiro",
      "url": "https://registry.npmjs.com",
      "scopes": [ "jp.keijiro" ]
    }
  ],
  "dependencies": {
    "jp.keijiro.dkvfx": "0.1.2",
    }
    }
but i'm still getting this error:
"Assets\jp.keijiro.dkvfx\Runtime\Converter.cs(1,7): error CS0246: The type or namespace name 'Klak' could not be found (are you missing a using directive or an assembly reference?)"

**Comment by keijiro** [comment]
Remove my packages (Dkvfx and KlakHAP) from the project directory. It will be installed via the package manager.

**Comment by Pitamor** [comment]
Thank you once again!
I've managed to import the package from the package manager but still cannot see the video.
I would be really appreciate to know that proper workflow of creating it properly on my own project.
here is a link to my unity project: https://we.tl/t-mogYRouv0d

Thanks once again

**Comment by Pitamor** [comment]
It's working! Thank you so much for your help!
