### ISSUE TITLE
Multiple Depthkit videos in one scene

### ISSUE THREAD

**Issue by cpkcpkcpk** [keijiro/Dkvfx#11]
Hi, I saw there is a closed case about this but I'm also having problems using multiple videos in one scene - e.g. 2 videos playing at the same with different graphs.

I have set everything up from scratch, but all the HAP players in my scene are referring the same converter, and there is only one set of color and position maps to use in VFX graph.

When you have multiple streams of Depthkit recordings playing at the same time, I'm guessing each clip should have it's own color and position maps? I can't think of another way to have multiple clips playing at the same time in different graphs.

Thanks,
Charlie

**Comment by keijiro** [comment]
Sorry but I can't understand what you're trying to do exactly. I think you understand that you should create multiple HAP players, multiple converters and multiple color/position maps. So, you should do so. Why did you use the same converter for the HAP players?

**Comment by cpkcpkcpk** [comment]
I'm trying to play 3 videos at the same time. I have multiple HAP players, converters and vfx graphs, but they all play the same video as only one set of color/position maps is generated by one of the converters (the lowest active converter in the heirarchy).

I would expect each converter to generate it's own color/position maps, similar to Pcx where importing 3 .ply files generates 3 different maps.

**Comment by keijiro** [comment]
Why do you use only a single pair of color/position maps? You should create three pairs of render texture assets, then assign them separately.

**Comment by cpkcpkcpk** [comment]
Ah sorry, I figured this out right after I replied. Duplicating the render texture assets and assigning them separately in each converter works great. Thanks!
