### ISSUE TITLE
Does the DKVFX can also work with the URP?

### ISSUE THREAD

**Issue by Pitamor** [keijiro/Dkvfx#12]
Hi Keijiro,

I'm working on a VR project combining Volumetric Videos. 
I'm creating my project with the Universal render pipeline and really want to use the VFX graph.
I've add the repositories and everything and I'm not getting any errors but it's also don't work...

Thanks a lot an advance

**Comment by keijiro** [comment]
Although the sample in this repository only works on HDRP, Dkvfx is compatible with URP.

In other words, you can't use the sample VFX in this repository with URP, but you can create your own VFX on URP with Dkvfx.

**Comment by Pitamor** [comment]
Ok, Great. Thank You!

One last question, How do I create a Metadata, color and position files for
my HAP File?
Is there an explanation somewhere?

Thanks again

‫בתאריך שבת, 7 בנוב׳ 2020 ב-3:23 מאת ‪Keijiro Takahashi‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by keijiro** [comment]
For metadata, see #3.

For color and position rendertexture, you can create your own ones https://docs.unity3d.com/Manual/class-RenderTexture.html

Note that you should use the same resolution as your exported video file.

**Comment by Pitamor** [comment]
Thanks! I did it but unfortunately it's still dont working and it's hard to
say why...
It looks exactly the same as it looks in the HDRP and I don't have any
errors...
I'm attaching some pictures that of how it is looks like

Huge Thanks Once again!


‫בתאריך שבת, 7 בנוב׳ 2020 ב-10:07 מאת ‪Keijiro Takahashi‬‏ <‪
notifications@github.com‬‏>:‬
