### ISSUE TITLE
Is it possible to crop particles ?

### ISSUE THREAD

**Issue by PockPocket** [keijiro/Dkvfx#16]
Hi again,

I was wondering if it was possible to crop a section out of my volumetric capture ? In other words, I'm trying to get rid of the particles in front of my capture, I tried with the boundary box and adjusting it's size but it didn't seemed to change anything.

Here's an image of what i'm trying to do:

![image](https://user-images.githubusercontent.com/73412598/114585336-886c1200-9c51-11eb-953a-9dd61e013327.png)

**Comment by keijiro** [comment]
The Kill block is handy for culling particles.

https://docs.unity3d.com/Packages/com.unity.visualeffectgraph@10.4/manual/Block-Kill(AABox).html?q=inside

**Comment by keijiro** [comment]
By the way, this issue tracker is dedicated to the issues relevant to the Dkvfx project. Please use Forum or other communities for general VFX questions.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
