### ISSUE TITLE
Multiple instances problem?

### ISSUE THREAD

**Issue by dvdsmthdvd** [keijiro/Dkvfx#19]
When I use multiple instances of the player/converter/vfx prefabs, each one updates with the new video. How can I use this with multiple instances and several different videos in the same scene?

**Comment by keijiro** [comment]
Did you add a pair of color/position render textures for each player? I guess that your players are overwriting the same color/position render textures.

**Comment by dvdsmthdvd** [comment]
Yes that solved it. Thank you so much for your help!
