### ISSUE TITLE
Multi-Sensor videos

### ISSUE THREAD

**Issue by ahfontaine** [keijiro/Dkvfx#20]
Hi!
I was wondering if this setup could theoretically work with multi-sensor videos? Would I need to create 10 different instances of the Converter + Render Textures? Should I be able to use the same one?

I'm trying to test with a 10-camera setup coming out of DepthKit and I'm unsure what exactly is wrong, if it's the metadata or my setup.

Thanks!

**Comment by keijiro** [comment]
I have never tried a multi-camera setup with DepthKit. So, I have no idea... Does DepthKit support multi-sensor? Does it export a single combined video file or 10 separated video files?

**Comment by ahfontaine** [comment]
Depthkit will output one video (in HapQ) with the 10 sensors playing at the same time. It's the same for any number of sensors : 1 video with everything.

**Comment by keijiro** [comment]
Thanks for the information. Then, it requires special care. Dkvfx only supports the one-stream-per-one-file format.

By the way, doesn't the current version of DepthKit support VFX Graph officially? I think there is no special reason to use Dkvfx anymore.

**Comment by keijiro** [comment]
I'm closing this issue as `won't fix`. My current stance on it is that we should use the official VFX Graph support rather than this plugin for multi-camera setups.
