### ISSUE TITLE
Multiple cameras

### ISSUE THREAD

**Issue by jabaez** [keijiro/Dkvfx#4]
How can I add another camera to your project with the same computer?

Great job!

Jose

**Comment by keijiro** [comment]
I think you can add another camera to your project as usual in Unity... Sorry, I can't understand what the point of your question is.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further issues.

**Comment by jabaez** [comment]
Ok, I will try to add a second camera to see if I can combine the point cloud. 
Thank you,
Jose
    On Monday, October 7, 2019, 09:43:03 PM CDT, Keijiro Takahashi <notifications@github.com> wrote:  
 
 
I think you can add another camera to your project as usual in Unity... Sorry, I can't understand what the point of your question is.
