### ISSUE TITLE
Hap conversion parameters

### ISSUE THREAD

**Issue by sergiobd** [keijiro/Dkvfx#5]
Hi Keijiro,

May I ask what tool/parameters are you using to convert depthkit exports to HAP?
I'm using ffmpeg from the MP4 that is exported from depthkit, like this:

ffmpeg -i input.mp4 -c:v hap output.mov

but somehow when I use this video (with the proper metadata), there is a strange warp in the pointcloud in Unity (as if the metadata and the depth data encoding to not match). I realized that if I export the video using Adobe Media Encoder this doesn't happen, so I wonder if there is some color encoding parameters that I'm missing...

**Comment by keijiro** [comment]
`ffmpeg -i input.mp4 -c:v hap output.mov`

That's correct. You're doing it in the right way, I've never experienced such an issue though.

How about updating ffmpeg version? I usually use Windows build distributed by Zeranoe.

https://ffmpeg.zeranoe.com/builds/

**Comment by sergiobd** [comment]
Thank you Keijiro. I realized that the problem was that I was not clipping the output of the VFX Graph, so there were some artifacts outside the clipping range.
