### ISSUE TITLE
different videos/assets in one scene

### ISSUE THREAD

**Issue by vinnie882** [keijiro/Dkvfx#6]
Dear Keijiro,

first of all, thank you for your dedication and creativity in creating this effect. I have a question:

Is it possible to stream different videos / assets in one scene? I tried to duplicate the VFX effect, the hap player and the converter und connecting them to each other but it seems that the Hap-Player is always referring to the same converter so that all players in the scene are streaming the same video.

I would love to hear from you. Could not find any usefull adise by googling. Thanks in advance!

Vincent

**Comment by keijiro** [comment]
In some previous projects, I used multiple streams of Deptkit recordings with Dkvfx, and it worked flawlessly. I recommend setting things up from scratch (not copy-pasting the example).

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it if you still have a problem with it.

**Comment by cpkcpkcpk** [comment]
Hi, I'm also having problems using multiple videos in one scene. I have set everything up from scratch, but all the HAP players are referring the same converter, and there is only one set of color and position maps to use in VFX graph.

When you have multiple streams of Depthkit recordings working at the same time, I'm guessing each clip should have it's own color and position maps?

Thanks,
Charlie
