### ISSUE TITLE
Best way to use Dkvfx with a modified version of KlakHap

### ISSUE THREAD

**Issue by sergiobd** [keijiro/Dkvfx#8]
Hi,

I want to introduce slight modifications on KlapHap in order to use them with DkVfx. However, KlakHap is a git-based dependency of Dkvfx, so my changes will be overwritten. When I try to import KlapHap locally, apparently DkVfx does not "see" KlakHap's namespace. What should be the best way of using a modified version of KlakHap with Dkvfx?

**Comment by keijiro** [comment]
The easiest way is to modify Dkvfx too. Make it depend to your own version of KlakHap.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
